- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1109/LCOMM.2023.3257136
  tags:
    - Code acceleration
    - Post-quantum cryptography
  plugin: sources.py
  file: sources.yaml


- id: eid:2-s2.0-85094432578
  title: 
  publisher: 
  date:
  link: 
  orcid: 
  plugin: sources.py
  file: sources.yaml
